spring:
  application:
    name: survey-service
  # Temporal Configuration
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workers:
      - name: survey-worker
        task-queue: survey_task_queue
    workersAutoDiscovery:
      packages:
        - com.example.myapp.workflows
        - com.example.myapp.activities


# Server Configuration
server:
  port: 8081
  servlet:
    context-path: /

# Logging configuration
logging:
  level:
    org.springframework: INFO
    io.temporal: INFO
    com.example.myapp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application-specific properties
app:
  # Maximum number of retry attempts for application logic
  max-retry-attempts: 3

  # Circuit breaker configuration
  circuit-breaker:
    failure-rate-threshold: 50
    wait-duration-in-open-state: 5s
    permitted-number-of-calls-in-half-open-state: 10
    sliding-window-size: 10
    minimum-number-of-calls: 5

  # Rate limiting
  rate-limit:
    capacity: 100
    refresh-period: 1s